DROP TABLE IF EXISTS asset_classes;

CREATE TABLE asset_classes (
  id INT NOT NULL AUTO_INCREMENT,
  description VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS asset_list;

CREATE TABLE asset_list (
  id INT NOT NULL AUTO_INCREMENT,
  asset_class INT NOT NULL,
  description VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS asset_log;

CREATE TABLE asset_log (
  id INT NOT NULL AUTO_INCREMENT,
  asset_id INT NOT NULL,
  epoch TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deposit_value DECIMAL(13,2) NOT NULL,
  asset_value DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS settings;

CREATE TABLE settings (
  setting VARCHAR(20) NOT NULL,
  value VARCHAR(20) NOT NULL,
  PRIMARY KEY (setting)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
