DROP TABLE IF EXISTS payments;

CREATE TABLE payments (
  id INT NOT NULL AUTO_INCREMENT,
  asset_id INT NOT NULL,
  epoch TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  amount DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
